package com.github.ilyashvetsov.recipes

const val ARG_CATEGORY_ID = "ARG_CATEGORY_ID"
const val ARG_CATEGORY_NAME = "ARG_CATEGORY_NAME"
const val ARG_CATEGORY_IMAGE_URL = "ARG_CATEGORY_IMAGE_URL"
const val ARG_RECIPE = "ARG_RECIPE"
const val SHARED_PREFS_SET_FAVORITES_RECIPE = "SHARED_PREFS_SET_FAVORITES_RECIPE"
const val FAVORITES_RECIPE_KEY = "FAVORITES_RECIPE_KEY"
