package com.github.ilyashvetsov.recipes.ui

const val ARG_RECIPE_ID = "ARG_RECIPE_ID"
const val SHARED_PREFS_SET_FAVORITES_RECIPE = "SHARED_PREFS_SET_FAVORITES_RECIPE"
const val FAVORITES_RECIPE_KEY = "FAVORITES_RECIPE_KEY"
